name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Ver archivos
        run: ls -la

      - name: Leer Dockerfile
        run: cat dockerfile

      - name: Build Docker image
        run: docker build -t backend-app:v1.0.0 .
      
      - name: Visualizar las imagenes de Docker
        run: docker images